#!/bin/bash
# =============================================================================
# export_knowledge.sh - 지식 내보내기 스크립트
# =============================================================================
# 사용법: ./scripts/export_knowledge.sh [format]
# format: md (기본), html, pdf
# =============================================================================

set -e

# 색상 정의
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }

# 프로젝트 루트
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

FORMAT="${1:-md}"
DATE=$(date +%Y-%m-%d)
EXPORT_DIR="exports"
EXPORT_FILE="$EXPORT_DIR/knowledge_export_$DATE"

echo ""
echo "============================================"
echo "  Knowledge Export"
echo "============================================"
echo ""

# Export 폴더 생성
mkdir -p "$EXPORT_DIR"

# 개념 이름 추출
CONCEPT_NAME=$(grep -m1 "^\*\*Name\*\*:" knowledge/00_CORE_CONCEPT.md 2>/dev/null | sed 's/\*\*Name\*\*://' | xargs || echo "Unknown Concept")

log_info "개념: $CONCEPT_NAME"
log_info "포맷: $FORMAT"

# Markdown 통합 파일 생성
log_info "Markdown 파일 생성 중..."

cat > "$EXPORT_FILE.md" << EOF
# Knowledge Export: $CONCEPT_NAME

**Export Date**: $DATE
**Generated by**: Learning Autopilot

---

# Table of Contents

1. [Core Concept](#core-concept)
2. [Mental Model](#mental-model)
3. [Deep Notes](#deep-notes)
4. [Analogy Map](#analogy-map)
5. [Application](#application)
6. [Questions](#questions)
7. [Mastery Score](#mastery-score)

---

EOF

# 각 knowledge 파일 추가
for file in knowledge/*.md; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        echo "" >> "$EXPORT_FILE.md"
        echo "---" >> "$EXPORT_FILE.md"
        echo "" >> "$EXPORT_FILE.md"
        cat "$file" >> "$EXPORT_FILE.md"
        echo "" >> "$EXPORT_FILE.md"
    fi
done

# Study Log 추가
cat >> "$EXPORT_FILE.md" << EOF

---

# Appendix: Study Log

EOF

if [ -f "logs/STUDY_LOG.md" ]; then
    cat "logs/STUDY_LOG.md" >> "$EXPORT_FILE.md"
fi

log_success "Markdown 내보내기 완료: $EXPORT_FILE.md"

# HTML 변환 (pandoc이 있는 경우)
if [ "$FORMAT" == "html" ] || [ "$FORMAT" == "all" ]; then
    if command -v pandoc &> /dev/null; then
        log_info "HTML 변환 중..."
        pandoc "$EXPORT_FILE.md" -o "$EXPORT_FILE.html" \
            --standalone \
            --metadata title="$CONCEPT_NAME - Knowledge Export" \
            --css="https://cdn.jsdelivr.net/npm/github-markdown-css/github-markdown.min.css" \
            2>/dev/null || log_warning "HTML 변환 실패"

        if [ -f "$EXPORT_FILE.html" ]; then
            log_success "HTML 내보내기 완료: $EXPORT_FILE.html"
        fi
    else
        log_warning "pandoc이 설치되어 있지 않습니다. HTML 변환 건너뜀."
    fi
fi

# PDF 변환 (pandoc + latex가 있는 경우)
if [ "$FORMAT" == "pdf" ] || [ "$FORMAT" == "all" ]; then
    if command -v pandoc &> /dev/null && command -v pdflatex &> /dev/null; then
        log_info "PDF 변환 중..."
        pandoc "$EXPORT_FILE.md" -o "$EXPORT_FILE.pdf" \
            --pdf-engine=pdflatex \
            -V geometry:margin=1in \
            2>/dev/null || log_warning "PDF 변환 실패"

        if [ -f "$EXPORT_FILE.pdf" ]; then
            log_success "PDF 내보내기 완료: $EXPORT_FILE.pdf"
        fi
    else
        log_warning "pandoc/pdflatex가 설치되어 있지 않습니다. PDF 변환 건너뜀."
    fi
fi

# 요약
echo ""
echo "============================================"
echo "  Export Complete!"
echo "============================================"
echo ""
echo "Files created:"
ls -la "$EXPORT_DIR"/*$DATE* 2>/dev/null || echo "  (none)"
echo ""
